#!/bin/bash
srcFile="$1"
outFile="$2"
defaultPythonVersion=$(python -c 'import sys; print(sys.version_info.major)')
if [[ $defaultPythonVersion == 3 ]]
then
    python kompilator.py "$srcFile" "$outFile"
else
    echo "Trying fallback Python version 3..."
    python3 kompilator.py "$srcFile" "$outFile"
fi